plugins {
    id 'java-library'
}

group = 'cn.liqing'
version = '4.0.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // 使用 Gson 替代 Jackson
    api 'com.google.code.gson:gson:2.11.0'
    api 'org.java-websocket:Java-WebSocket:1.5.7'
    
    // 编译时依赖
    compileOnly 'org.jetbrains:annotations:26.0.1'
    compileOnly 'org.slf4j:slf4j-api:2.0.16'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    
    withSourcesJar()
    withJavadocJar()
}

test {
    useJUnitPlatform()
}