plugins {
    id 'java'
    id 'application'
}

group = 'cn.liqing.example'
version = '1.0'

repositories {
    mavenLocal()  // 首先从本地 Maven 仓库查找
    mavenCentral()
}

dependencies {
    implementation 'cn.liqing:bili-live-danmu:4.0.0'
    implementation 'org.slf4j:slf4j-simple:2.0.16'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'cn.liqing.example.SimpleLiveRoomTest'
}

// 配置运行任务
run {
    standardInput = System.in
}
